-- Phase 6b3: Ownership activity types (ACK / CLAIM / ASSIGN vocabulary).

ALTER TYPE "SecurityEventActivityType" ADD VALUE IF NOT EXISTS 'ATTENTION_ACKNOWLEDGED';
ALTER TYPE "SecurityEventActivityType" ADD VALUE IF NOT EXISTS 'ATTENTION_CLAIMED';
ALTER TYPE "SecurityEventActivityType" ADD VALUE IF NOT EXISTS 'ATTENTION_CLAIM_RELEASED';
ALTER TYPE "SecurityEventActivityType" ADD VALUE IF NOT EXISTS 'ATTENTION_CLAIM_TRANSFERRED';

ALTER TYPE "InvestigationActivityType" ADD VALUE IF NOT EXISTS 'CLAIMED';
ALTER TYPE "InvestigationActivityType" ADD VALUE IF NOT EXISTS 'CLAIM_RELEASED';
ALTER TYPE "InvestigationActivityType" ADD VALUE IF NOT EXISTS 'CLAIM_TRANSFERRED';
